#!/bin/bash

rm -rf root
mkdir -p root/MyApp.app
cp -r src/* root/MyApp.app/
chmod a+x root/MyApp.app/Contents/MacOS/MyApp
pkgbuild --analyze --root root MyApp.plist
pkgbuild --root root --component-plist MyApp.plist --install-location /Applications --identifier com.myapp --version 0.1.1 MyApp.pkg
